apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: server
          imagePullPolicy: IfNotPresent
          name: webserver
          env:
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: webserver-configmap
                  key: greeting
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort